# Generated by Django 5.1.5 on 2025-03-25 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="application_forms",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("pdf_date", models.DateField()),
                ("file", models.FileField(upload_to="media/pdfs/")),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_th",
                    models.CharField(max_length=255, verbose_name="ชื่อหน่วยงาน (ไทย)"),
                ),
                (
                    "name_en",
                    models.CharField(max_length=255, verbose_name="ชื่อหน่วยงาน (อังกฤษ)"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="E-mail หน่วยงาน"),
                ),
                (
                    "website",
                    models.URLField(blank=True, verbose_name="Website หน่วยงาน"),
                ),
                (
                    "company_types",
                    models.CharField(
                        choices=[
                            ("public", "รัฐวิสาหกิจ"),
                            ("private", "เอกชน"),
                            ("government", "ราชการ"),
                        ],
                        max_length=50,
                        verbose_name="ประเภทหน่วยงาน",
                    ),
                ),
                ("description", models.TextField(verbose_name="เกี่ยวกับการประกอบการ")),
                (
                    "head_name",
                    models.CharField(max_length=255, verbose_name="ชื่อหัวหน้าหน่วยงาน"),
                ),
                (
                    "head_position",
                    models.CharField(max_length=100, verbose_name="ตำแหน่ง"),
                ),
                (
                    "address_no",
                    models.CharField(max_length=100, verbose_name="ที่ตั้ง เลขที่"),
                ),
                (
                    "address_moo",
                    models.CharField(blank=True, max_length=100, verbose_name="หมู่ที่"),
                ),
                (
                    "address_building",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ชื่ออาคาร"
                    ),
                ),
                (
                    "address_soi",
                    models.CharField(blank=True, max_length=100, verbose_name="ซอย"),
                ),
                (
                    "address_road",
                    models.CharField(blank=True, max_length=100, verbose_name="ถนน"),
                ),
                ("province", models.CharField(max_length=100, verbose_name="จังหวัด")),
                ("district", models.CharField(max_length=100, verbose_name="อำเภอ")),
                ("subdistrict", models.CharField(max_length=100, verbose_name="ตำบล")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="รหัสไปรษณีย์"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="โทรศัพท์")),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("partner", "พาร์ทเนอร์"),
                            ("no-partner", "ไม่ใช่พาร์ทเนอร์"),
                        ],
                        max_length=50,
                        verbose_name="ประเภทบริษัท",
                    ),
                ),
                (
                    "company_file",
                    models.FileField(upload_to="uploads/", verbose_name="ไฟล์แนบ"),
                ),
                (
                    "company_date_add",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="วันที่เพิ่มข้อมูลบริษัท"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("job_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "job_posted",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="วันที่ประกาศงาน"
                    ),
                ),
                (
                    "job_updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="วันที่ปรับปรุงข้อมูล"
                    ),
                ),
                ("job_quantity", models.IntegerField(verbose_name="จำนวนที่เปิดรับสมัคร")),
                ("job_description", models.TextField(verbose_name="รายละเอียดงาน")),
                ("job_skill", models.TextField(verbose_name="ทักษะที่ต้องการ")),
                (
                    "job_department",
                    models.CharField(max_length=255, verbose_name="สาขาวิชา"),
                ),
                (
                    "job_file",
                    models.FileField(upload_to="uploads/", verbose_name="ไฟล์แนบ"),
                ),
                (
                    "job_status",
                    models.CharField(
                        choices=[("open", "เปิดรับสมัคร"), ("closed", "ปิดรับสมัคร")],
                        max_length=50,
                        verbose_name="สถานะ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Jobbenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("saraly", models.CharField(max_length=50, verbose_name="เงินเดือน")),
                ("lunch", models.CharField(max_length=50, verbose_name="อาหารกลางวัน")),
                ("delivery", models.CharField(max_length=50, verbose_name="รถรับ-ส่ง")),
            ],
        ),
        migrations.CreateModel(
            name="JobPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type", models.CharField(max_length=50, verbose_name="ตำแหน่งงาน")),
            ],
        ),
        migrations.CreateModel(
            name="Company_image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="static/images/"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                        verbose_name="ชื่อหน่วยงาน",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HumanResouce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(max_length=255, verbose_name="ชื่อผู้ประสานงาน"),
                ),
                (
                    "contact_position",
                    models.CharField(max_length=100, verbose_name="ตำแหน่ง"),
                ),
                (
                    "contact_department",
                    models.CharField(max_length=100, verbose_name="แผนก/หน่วย/ฝ่าย"),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="E-mail ผู้ประสานงาน"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=20, verbose_name="โทรศัพท์ผู้ประสานงาน"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                        verbose_name="หน่วยงาน",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้งาน",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HumnanResource_Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "HumanResouce",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.humanresouce",
                        verbose_name="ผู้ประสานงาน",
                    ),
                ),
                (
                    "Job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.job",
                        verbose_name="ตำแหน่งงาน",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="job_welfare_benefit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.jobbenefit",
                verbose_name="สวัสดิการ",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="main.jobposition",
                verbose_name="ชื่อตำแหน่งงาน",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommend", models.BooleanField()),
                ("overall_rating", models.IntegerField()),
                ("benefits_rating", models.IntegerField()),
                ("environment_rating", models.IntegerField()),
                ("management_rating", models.IntegerField()),
                ("job_type", models.CharField(max_length=255)),
                ("job_description", models.TextField()),
                ("experience", models.TextField()),
                ("advice", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.company"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="ชื่อนิสิต")),
                ("student_id", models.CharField(max_length=20, verbose_name="รหัสนิสิต")),
                (
                    "field_of_study",
                    models.CharField(max_length=255, verbose_name="สาขาวิชา"),
                ),
                ("year", models.IntegerField(verbose_name="ชั้นปี")),
                (
                    "advisor",
                    models.CharField(max_length=255, verbose_name="อาจารย์ที่ปรึกษา"),
                ),
                (
                    "academic_year",
                    models.CharField(max_length=9, verbose_name="ปีการศึกษา"),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2")],
                        max_length=10,
                        verbose_name="ภาคเรียน",
                    ),
                ),
                ("gpa_term", models.FloatField(verbose_name="เกรดเฉลี่ยภาคเรียนที่ผ่านมา")),
                ("gpa_total", models.FloatField(verbose_name="เกรดเฉลี่ยรวม")),
                (
                    "internship_start_date",
                    models.DateField(verbose_name="วันที่เริ่มปฏิบัติงาน"),
                ),
                (
                    "internship_end_date",
                    models.DateField(verbose_name="วันที่สิ้นสุดปฏิบัติงาน"),
                ),
                (
                    "id_card",
                    models.CharField(
                        max_length=13, verbose_name="บัตรประจำตัวประชาชนเลขที่"
                    ),
                ),
                ("id_card_issue_date", models.DateField(verbose_name="วันที่ออกบัตร")),
                ("id_card_expiry_date", models.DateField(verbose_name="วันที่บัตรหมดอายุ")),
                ("national", models.CharField(max_length=50, verbose_name="เชื้อชาติ")),
                ("citizenship", models.CharField(max_length=50, verbose_name="สัญชาติ")),
                ("religion", models.CharField(max_length=50, verbose_name="ศาสนา")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "ชาย"), ("female", "หญิง"), ("other", "อื่นๆ")],
                        max_length=10,
                        verbose_name="เพศ",
                    ),
                ),
                ("height", models.IntegerField(verbose_name="ส่วนสูง (cm.)")),
                ("weight", models.IntegerField(verbose_name="น้ำหนัก (kg.)")),
                (
                    "disease",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="โรคประจำตัว (ถ้ามี)"
                    ),
                ),
                ("address", models.TextField(verbose_name="ที่อยู่ปัจจุบัน")),
                (
                    "mobile_phone",
                    models.CharField(max_length=20, verbose_name="โทรศัพท์มือถือ"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "emergency_contact",
                    models.CharField(
                        max_length=255, verbose_name="บุคคลที่ติดต่อได้ในกรณีฉุกเฉิน"
                    ),
                ),
                (
                    "relationship",
                    models.CharField(max_length=50, verbose_name="ความเกี่ยวข้องเป็น"),
                ),
                (
                    "emergency_phone",
                    models.CharField(max_length=20, verbose_name="โทรศัพท์"),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="uploads/", verbose_name="รูปถ่าย"),
                ),
                (
                    "resume",
                    models.FileField(upload_to="uploads/", verbose_name="Resume"),
                ),
                (
                    "transcript",
                    models.FileField(upload_to="uploads/", verbose_name="Transcript"),
                ),
                (
                    "activity_transcript",
                    models.FileField(
                        upload_to="uploads/", verbose_name="Activity Transcript"
                    ),
                ),
                (
                    "soldier",
                    models.CharField(
                        choices=[
                            ("ผ่านการเกณฑ์ทหาร", "ผ่านการเกณฑ์ทหาร"),
                            ("ยังไม่ผ่านการเกณฑ์ทหาร", "ยังไม่ผ่านการเกณฑ์ทหาร"),
                            ("ได้รับการยกเว้น", "ได้รับการยกเว้น"),
                        ],
                        max_length=50,
                        verbose_name="สถานะทหาร",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ผู้ใช้งาน",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student_job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.job",
                        verbose_name="ตำแหน่งงาน",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.student",
                        verbose_name="นิสิต",
                    ),
                ),
            ],
        ),
    ]
