# Generated by Django 5.1.7 on 2025-03-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('username_pn', models.CharField(max_length=255, unique=True)),
                ('password_pn', models.CharField(max_length=255)),
                ('email_pn', models.EmailField(max_length=254, unique=True)),
                ('image_pn', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('name_en', models.CharField(max_length=255)),
                ('name_th', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('description_pn', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
