# Generated by Django 5.1.7 on 2025-03-27 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='main.company', verbose_name='ชื่อหน่วยงาน'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='static/images/', verbose_name='โลโก้หน่วยงาน'),
        ),
    ]
