# Generated by Django 5.1.5 on 2025-03-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application_forms',
            old_name='student_id',
            new_name='student',
        ),
    ]
