# Generated by Django 5.1.5 on 2025-03-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_check', '0002_rename_student_id_application_forms_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_forms',
            name='status',
            field=models.CharField(choices=[('pending', 'รอการตรวจสอบ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20),
        ),
    ]
