# Generated by Django 5.1.5 on 2025-03-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_check', '0003_application_forms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_forms',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
