# Generated by Django 5.1.5 on 2025-03-02 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.BooleanField()),
                ('overall_rating', models.IntegerField()),
                ('benefits_rating', models.IntegerField()),
                ('environment_rating', models.IntegerField()),
                ('management_rating', models.IntegerField()),
                ('job_type', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('experience', models.TextField()),
                ('advice', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.company')),
            ],
        ),
    ]
