# Generated by Django 5.1.5 on 2026-04-03 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('ai_engineer', 'AI Engineer'), ('automation_engineer', 'Automation Engineer'), ('backend_developer', 'Backend Developer'), ('blockchain_developer', 'Blockchain Developer'), ('cloud_engineer', 'Cloud Engineer'), ('computer_vision_engineer', 'Computer Vision Engineer'), ('cybersecurity_analyst', 'Cybersecurity Analyst'), ('data_analyst', 'Data Analyst'), ('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('database_administrator', 'Database Administrator'), ('devops_engineer', 'DevOps Engineer'), ('embedded_software_engineer', 'Embedded Software Engineer'), ('frontend_developer', 'Frontend Developer'), ('fullstack_developer', 'Full Stack Developer'), ('game_developer', 'Game Developer'), ('game_engine_programmer', 'Game Engine Programmer'), ('hardware_engineer', 'Hardware Engineer'), ('iot_developer', 'IoT Developer'), ('machine_learning_engineer', 'Machine Learning Engineer'), ('mobile_developer', 'Mobile Developer'), ('network_administrator', 'Network Administrator'), ('network_engineer', 'Network Engineer'), ('qa_engineer', 'QA Engineer'), ('robotics_engineer', 'Robotics Engineer'), ('security_engineer', 'Security Engineer'), ('site_reliability_engineer', 'Site Reliability Engineer (SRE)'), ('software_architect', 'Software Architect'), ('software_engineer', 'Software Engineer'), ('software_test_engineer', 'Software Test Engineer'), ('solutions_architect', 'Solutions Architect'), ('systems_administrator', 'Systems Administrator'), ('systems_architect', 'Systems Architect'), ('ui_ux_designer', 'UI/UX Designer'), ('web_developer', 'Web Developer')], max_length=50, verbose_name='ตำแหน่งงาน')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='ชื่อหน่วยงาน (ไทย)')),
                ('name_en', models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='ชื่อหน่วยงาน (อังกฤษ)')),
                ('email', models.EmailField(blank=True, default='-', max_length=254, null=True, verbose_name='E-mail หน่วยงาน')),
                ('website', models.URLField(blank=True, default='-', null=True, verbose_name='Website หน่วยงาน')),
                ('company_type', models.CharField(blank=True, choices=[('partner', 'พาร์ทเนอร์'), ('no-partner', 'ไม่ใช่พาร์ทเนอร์')], max_length=50, null=True, verbose_name='ประเภทบริษัท')),
                ('description', models.TextField(blank=True, default='-', null=True, verbose_name='เกี่ยวกับการประกอบการ')),
                ('head_name', models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='ชื่อหัวหน้าหน่วยงาน')),
                ('head_position', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ตำแหน่ง')),
                ('address_no', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ที่ตั้ง เลขที่')),
                ('address_moo', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='หมู่ที่')),
                ('address_building', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ชื่ออาคาร')),
                ('address_soi', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ซอย')),
                ('address_road', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ถนน')),
                ('province', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='จังหวัด')),
                ('district', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='อำเภอ')),
                ('subdistrict', models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ตำบล')),
                ('postal_code', models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='รหัสไปรษณีย์')),
                ('phone', models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='โทรศัพท์')),
                ('company_file', models.FileField(blank=True, default='-', null=True, upload_to='uploads/companyfile/', verbose_name='ไฟล์แนบ')),
                ('company_date_add', models.DateTimeField(auto_now_add=True, null=True, verbose_name='วันที่เพิ่มข้อมูลบริษัท')),
                ('logo', models.ImageField(blank=True, default='-', null=True, upload_to='uploads/company-logo', verbose_name='โลโก้หน่วยงาน')),
                ('company_own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='ชื่อหน่วยงาน')),
            ],
        ),
        migrations.CreateModel(
            name='HumanResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255, verbose_name='ชื่อผู้ประสานงาน')),
                ('contact_position', models.CharField(max_length=100, verbose_name='ตำแหน่ง')),
                ('contact_department', models.CharField(max_length=100, verbose_name='แผนก/หน่วย/ฝ่าย')),
                ('contact_email', models.EmailField(blank=True, default='-', max_length=254, null=True, verbose_name='E-mail ผู้ประสานงาน')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='โทรศัพท์ผู้ประสานงาน')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='หน่วยงาน')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งาน')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_posted', models.DateTimeField(auto_now_add=True, null=True, verbose_name='วันที่ประกาศงาน')),
                ('job_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='วันที่ปรับปรุงข้อมูล')),
                ('job_quantity', models.IntegerField(blank=True, null=True, verbose_name='จำนวนที่เปิดรับสมัคร')),
                ('job_description', models.TextField(blank=True, default='-', null=True, verbose_name='รายละเอียดงาน')),
                ('job_skill', models.TextField(blank=True, default='-', null=True, verbose_name='ทักษะที่ต้องการ')),
                ('job_department', models.CharField(blank=True, max_length=255, null=True, verbose_name='สาขาวิชา')),
                ('job_welfare_benefit', models.TextField(blank=True, default='-', max_length=255, null=True, verbose_name='สวัสดิการ')),
                ('job_file', models.FileField(blank=True, default='-', null=True, upload_to='uploads/', verbose_name='ไฟล์แนบ')),
                ('job_status', models.CharField(blank=True, choices=[('open', 'เปิดรับสมัคร'), ('closed', 'ปิดรับสมัคร')], max_length=50, null=True, verbose_name='สถานะ')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='บริษัท')),
                ('job_name', models.ForeignKey(blank=True, default='-', null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.jobposition', verbose_name='ชื่อตำแหน่งงาน')),
            ],
        ),
        migrations.CreateModel(
            name='HumanResourceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.humanresource', verbose_name='ผู้ประสานงาน')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.job', verbose_name='ตำแหน่งงาน')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommend', models.BooleanField(verbose_name='ระดับการแนะนำ')),
                ('overall_rating', models.IntegerField(verbose_name='ภาพรวม')),
                ('benefits_rating', models.IntegerField(verbose_name='สวัสดิการ')),
                ('environment_rating', models.IntegerField(verbose_name='สภาพแวดล้อม')),
                ('management_rating', models.IntegerField(verbose_name='การบริหาร')),
                ('job_type', models.CharField(max_length=255, verbose_name='ตำแหน่งงาน')),
                ('job_description', models.TextField(verbose_name='รายละเอียดงาน')),
                ('experience', models.TextField(verbose_name='ประสบการณ์ที่ได้รับ')),
                ('advice', models.TextField(verbose_name='คำแนะนำ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company', verbose_name='บริษัท')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อนิสิต')),
                ('student_id', models.CharField(max_length=20, verbose_name='รหัสนิสิต')),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True, verbose_name='สาขาวิชา')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='ชั้นปี')),
                ('advisor', models.CharField(blank=True, max_length=255, null=True, verbose_name='อาจารย์ที่ปรึกษา')),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True, verbose_name='ปีการศึกษา')),
                ('semester', models.CharField(blank=True, choices=[('1', '1'), ('2', '2')], max_length=10, null=True, verbose_name='ภาคเรียน')),
                ('gpa_term', models.FloatField(blank=True, null=True, verbose_name='เกรดเฉลี่ยภาคเรียนที่ผ่านมา')),
                ('gpa_total', models.FloatField(blank=True, null=True, verbose_name='เกรดเฉลี่ยรวม')),
                ('internship_start_date', models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มปฏิบัติงาน')),
                ('internship_end_date', models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดปฏิบัติงาน')),
                ('id_card', models.CharField(blank=True, max_length=13, null=True, verbose_name='บัตรประจำตัวประชาชนเลขที่')),
                ('id_card_issue_date', models.DateField(blank=True, null=True, verbose_name='วันที่ออกบัตร')),
                ('id_card_expiry_date', models.DateField(blank=True, null=True, verbose_name='วันที่บัตรหมดอายุ')),
                ('national', models.CharField(blank=True, max_length=50, null=True, verbose_name='เชื้อชาติ')),
                ('citizenship', models.CharField(blank=True, max_length=50, null=True, verbose_name='สัญชาติ')),
                ('religion', models.CharField(blank=True, max_length=50, null=True, verbose_name='ศาสนา')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ชาย'), ('female', 'หญิง'), ('other', 'อื่นๆ')], max_length=10, null=True, verbose_name='เพศ')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='ส่วนสูง (cm.)')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='น้ำหนัก (kg.)')),
                ('disease', models.CharField(blank=True, max_length=255, verbose_name='โรคประจำตัว (ถ้ามี)')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่ปัจจุบัน')),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='โทรศัพท์มือถือ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('emergency_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='บุคคลที่ติดต่อได้ในกรณีฉุกเฉิน')),
                ('relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='ความเกี่ยวข้องเป็น')),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='โทรศัพท์')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/student-image/', verbose_name='รูปถ่าย')),
                ('resume', models.FileField(blank=True, null=True, upload_to='uploads/student-resume/', verbose_name='Resume')),
                ('transcript', models.FileField(blank=True, null=True, upload_to='uploads/student-transcript/', verbose_name='Transcript')),
                ('activity_transcript', models.FileField(blank=True, null=True, upload_to='uploads/student-activity-transcript/', verbose_name='Activity Transcript')),
                ('soldier', models.CharField(blank=True, choices=[('ผ่านการเกณฑ์ทหาร', 'ผ่านการเกณฑ์ทหาร'), ('ยังไม่ผ่านการเกณฑ์ทหาร', 'ยังไม่ผ่านการเกณฑ์ทหาร'), ('ได้รับการยกเว้น', 'ได้รับการยกเว้น')], max_length=50, null=True, verbose_name='สถานะทหาร')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='application_forms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_date', models.DateField()),
                ('pdf_file', models.FileField(upload_to='pdfs/application_forms/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('pending', 'รอการตรวจสอบ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.company')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.job', verbose_name='ตำแหน่งงาน')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.student', verbose_name='นิสิต')),
            ],
        ),
    ]
