# Generated by Django 5.1.7 on 2025-03-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่ออาคาร'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_moo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='หมู่ที่'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ที่ตั้ง เลขที่'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_road',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ถนน'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_soi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ซอย'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_date_add',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='วันที่เพิ่มข้อมูลบริษัท'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/companyfile/', verbose_name='ไฟล์แนบ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('partner', 'พาร์ทเนอร์'), ('no-partner', 'ไม่ใช่พาร์ทเนอร์')], max_length=50, null=True, verbose_name='ประเภทบริษัท'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='เกี่ยวกับการประกอบการ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='อำเภอ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail หน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อหัวหน้าหน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่ง'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/company-logo', verbose_name='โลโก้หน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อหน่วยงาน (อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_th',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อหน่วยงาน (ไทย)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AlterField(
            model_name='company',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subdistrict',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำบล'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website หน่วยงาน'),
        ),
    ]
