# Generated by Django 5.1.7 on 2025-03-28 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_forms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_date', models.DateField()),
                ('pdf_file', models.FileField(upload_to='media/pdfs/')),
                ('status', models.CharField(choices=[('pending', 'รอการตรวจสอบ'), ('approved', 'อนุมัติ'), ('rejected', 'ปฏิเสธ')], default='pending', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.student')),
            ],
        ),
        migrations.DeleteModel(
            name='ApplicationForm',
        ),
    ]
