# Generated by Django 5.1.7 on 2025-03-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_application_forms_delete_applicationform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_forms',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/application_forms/%Y/%m/%d/'),
        ),
    ]
