# Generated by Django 5.1.7 on 2025-03-28 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_alter_application_forms_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_forms',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.company'),
            preserve_default=False,
        ),
    ]
