# Generated by Django 5.1.7 on 2025-03-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_company_company_own'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanresource',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail ผู้ประสานงาน'),
        ),
    ]
