# Generated by Django 5.1.7 on 2025-03-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_humanresource_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='job_type',
            field=models.CharField(max_length=50, verbose_name='ตำแหน่งงาน'),
        ),
    ]
