# Generated by Django 5.1.7 on 2025-03-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_alter_jobposition_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='job_type',
            field=models.CharField(choices=[('ai_engineer', 'AI Engineer'), ('automation_engineer', 'Automation Engineer'), ('backend_developer', 'Backend Developer'), ('blockchain_developer', 'Blockchain Developer'), ('cloud_engineer', 'Cloud Engineer'), ('computer_vision_engineer', 'Computer Vision Engineer'), ('cybersecurity_analyst', 'Cybersecurity Analyst'), ('data_analyst', 'Data Analyst'), ('data_engineer', 'Data Engineer'), ('data_scientist', 'Data Scientist'), ('database_administrator', 'Database Administrator'), ('devops_engineer', 'DevOps Engineer'), ('embedded_software_engineer', 'Embedded Software Engineer'), ('frontend_developer', 'Frontend Developer'), ('fullstack_developer', 'Full Stack Developer'), ('game_developer', 'Game Developer'), ('game_engine_programmer', 'Game Engine Programmer'), ('hardware_engineer', 'Hardware Engineer'), ('iot_developer', 'IoT Developer'), ('machine_learning_engineer', 'Machine Learning Engineer'), ('mobile_developer', 'Mobile Developer'), ('network_administrator', 'Network Administrator'), ('network_engineer', 'Network Engineer'), ('qa_engineer', 'QA Engineer'), ('robotics_engineer', 'Robotics Engineer'), ('security_engineer', 'Security Engineer'), ('site_reliability_engineer', 'Site Reliability Engineer (SRE)'), ('software_architect', 'Software Architect'), ('software_engineer', 'Software Engineer'), ('software_test_engineer', 'Software Test Engineer'), ('solutions_architect', 'Solutions Architect'), ('systems_administrator', 'Systems Administrator'), ('systems_architect', 'Systems Architect'), ('ui_ux_designer', 'UI/UX Designer'), ('web_developer', 'Web Developer')], max_length=50, verbose_name='ตำแหน่งงาน'),
        ),
    ]
