# Generated by Django 5.1.7 on 2025-03-29 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_jobposition_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สาขาวิชา'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True, verbose_name='รายละเอียดงาน'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='ไฟล์แนบ'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.jobposition', verbose_name='ชื่อตำแหน่งงาน'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='จำนวนที่เปิดรับสมัคร'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_skill',
            field=models.TextField(blank=True, null=True, verbose_name='ทักษะที่ต้องการ'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(blank=True, choices=[('open', 'เปิดรับสมัคร'), ('closed', 'ปิดรับสมัคร')], max_length=50, null=True, verbose_name='สถานะ'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_welfare_benefit',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='สวัสดิการ'),
        ),
    ]
