# Generated by Django 5.1.7 on 2025-03-29 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_alter_job_job_department_alter_job_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_building',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ชื่ออาคาร'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_moo',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='หมู่ที่'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_no',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ที่ตั้ง เลขที่'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_road',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ถนน'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address_soi',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ซอย'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_file',
            field=models.FileField(blank=True, default='-', null=True, upload_to='uploads/companyfile/', verbose_name='ไฟล์แนบ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='เกี่ยวกับการประกอบการ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='district',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='อำเภอ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default='-', max_length=254, null=True, verbose_name='E-mail หน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_name',
            field=models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='ชื่อหัวหน้าหน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='company',
            name='head_position',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ตำแหน่ง'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='-', null=True, upload_to='uploads/company-logo', verbose_name='โลโก้หน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_en',
            field=models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='ชื่อหน่วยงาน (อังกฤษ)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name_th',
            field=models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='ชื่อหน่วยงาน (ไทย)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, default='-', max_length=20, null=True, verbose_name='โทรศัพท์'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AlterField(
            model_name='company',
            name='province',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='จังหวัด'),
        ),
        migrations.AlterField(
            model_name='company',
            name='subdistrict',
            field=models.CharField(blank=True, default='-', max_length=100, null=True, verbose_name='ตำบล'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, default='-', null=True, verbose_name='Website หน่วยงาน'),
        ),
        migrations.AlterField(
            model_name='humanresource',
            name='contact_email',
            field=models.EmailField(blank=True, default='-', max_length=254, null=True, verbose_name='E-mail ผู้ประสานงาน'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='รายละเอียดงาน'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_file',
            field=models.FileField(blank=True, default='-', null=True, upload_to='uploads/', verbose_name='ไฟล์แนบ'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.ForeignKey(blank=True, default='-', null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.jobposition', verbose_name='ชื่อตำแหน่งงาน'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_skill',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='ทักษะที่ต้องการ'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_welfare_benefit',
            field=models.TextField(blank=True, default='-', max_length=255, null=True, verbose_name='สวัสดิการ'),
        ),
    ]
