# Generated by Django 5.1.7 on 2025-03-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_alter_job_job_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_file',
            field=models.FileField(blank=True, default='-', null=True, upload_to='uploads/', verbose_name='ไฟล์แนบ'),
        ),
    ]
