# Generated by Django 5.1.7 on 2025-03-29 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0014_alter_job_job_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.student', verbose_name='นิสิต'),
            preserve_default=False,
        ),
    ]
