# Generated by Django 5.1.7 on 2025-03-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0015_review_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='student',
        ),
    ]
