# Generated by Django 5.1.6 on 2025-03-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='วันที่ปรับปรุงข้อมูล'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_welfare_benefit',
            field=models.TextField(max_length=255, null=True, verbose_name='สวัสดิการ'),
        ),
    ]
