# Generated by Django 5.1.6 on 2025-03-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0002_alter_job_job_updated_alter_job_job_welfare_benefit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_updated',
            field=models.DateTimeField(null=True, verbose_name='วันที่ปรับปรุงข้อมูล'),
        ),
    ]
